language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://albertowar.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "fXjjP9Bq6xMRjjBqnoSD4GhmOuCjN0SE057oBDBu3+27mIg9SrhZv7mi1cLZm4MbSgeaKp2i8+Dr8SIymeTRYPhmJai1v1bcrvJ0SfDvy7+Q14dOyA5M/QL15B8yBbRZdXPM0L2Bq+z+ux0X/vmFf7vvd/uVRPI9FP2+ew9mdiKXhNCxY0Ku6PmOcePaya/ZbU+xPCyr5/vYp2Zgu6UKuNaLTM/JpdQ5jIiLMZvF1NmEj6XYG9Y+UKI23wxQDMK3xfM7sPA9EcFqByuLHSR90z/QFVbnYk4F9rrMRtPDzXaMH9/kFvVnzIUq8i2aKrpcR6qxS2vqVbYBCgJ2tRN4kC8kowtlv7+4M4Z5MlVEbEBdJjzeNWQBGDm68kC90LU7cMnloGe6QJOFlqGV0427HqgUoEWp8DAv0jlz5jHV76HMbGqz6Ebww4FXf6V17upytuLU89q0+4ulLQoFQrFwPon02ylA6f1yAVaXF5ki+Wwluy+2WzTwQiergFxgdImB6OMgvChEqdWfhlID3k1ltHCH1YXw8C6Tmi1Fzg3cvoGUC5aRH/z5xJ5qDUElYOceZcNjPF1n4UpEqJc6BLkOrjG5KtQO2tDhveRDcbuUiIabtyHgM8SUMUiopilpNKcztahQBie+ksMe1LlUVz3CogMIqrfb/RrcjYPPdSP1kqI="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
